branch-defaults:
  master:
    environment: NodeEbCircleci-env
global:
  application_name: Node-EB-CircleCI
  default_ec2_keyname: e-4adh7t5cpu
  default_platform: Node.js running on 64bit Amazon Linux/4.13.1
  default_region: us-east-2
  sc: git
